### ISSUE TITLE
Fully Implement Marking Scheme

### ISSUE THREAD

**Issue by kuzi117** [cmput415/Tester#13]
We need to be able to "competitively test" student's solutions. This is a super task for the following:

- [x] Make test packages  (#1)
- [x] Multiple toolchains (for the same solution, as in scalc) (#14)
- [x] Multiple toolchains (for each student's solution) (#15)
- [x] Scoring system
